services:
  - type: web
    name: mars-gpu-viewer
    runtime: python3
    startCommand: "python3 server.py $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /
    autoDeploy: true